CREATE TABLE post(
    POST_ID         BIGINT AUTO_INCREMENT 			   PRIMARY KEY,
    IMAGE_ID        VARCHAR(255)                       NOT NULL,
    UPLOADER_ID     BIGINT                             NOT NULL,
    UPLOAD_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
    CONTENTS        TEXT                               NULL
);

CREATE TABLE user(
    USER_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255)          NOT NULL,
    EMAIL    VARCHAR(255)          NOT NULL,
    PASSWORD VARCHAR(255)          NOT NULL
);

CREATE TABLE follow(
    FOLLOW_ID          BIGINT AUTO_INCREMENT              PRIMARY KEY,
    USER_ID            BIGINT                             NOT NULL,
    FOLLOWER_ID        BIGINT                             NOT NULL,
    FOLLOW_DATETIME    DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
    MAIL_SENT_DATETIME DATETIME DEFAULT NULL
);